name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload everything in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
